# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'CocoaReactComponentKitApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaReactComponentKitApp
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'BKRedux'
  pod 'BKEventBus'
  pod 'SnapKit'
  
  target 'CocoaReactComponentKit' do
      inherit! :search_paths
  end
  
end
